
services:
  #qbitorrent:
  #  build: ./qbittorrent-plugins
  #  container_name: qbittorrent
  #  user: 1002:1002 
  #  ports:
  #    - 8080:8080
  #    - 6881:6881/tcp
  #    - 6881:6881/udp
  #  networks:
  #    - jackett-net:
  #  volumes:
  #    - ./qbit-config:/config
  #    - ./torrents:/torrents
  #    - /data/hdd/torrents:/downloads
  #    - type: bind
  #      source: ./engines/jackett.json
  #      target: /engines/jackett.json      
  #          # - ./engines:/engines
  #  restart: always

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=1002
      - PGID=1002
      - TZ=Europe/Rome
      - WEBUI_PORT=8080
    volumes:
      - qbit-config:/config
      - torrents:/torrents
      - /data/hdd/torrents:/downloads
      - ./engines:/config/qBittorrent/nova3/engines
    ports:
      - 8080:8080
      - 6881:6881
      - 6881:6881/udp
    networks:
      jackett-net:
    restart: unless-stopped

  jackett:
    image: lscr.io/linuxserver/jackett:latest
    container_name: jackett
    environment:
      - PUID=1002
      - PGID=1002
      - TZ=Europe/Rome
      - AUTO_UPDATE=true #optional
        #- RUN_OPTS=<run options here> #optional
    volumes:
      - jackett-config:/config
      - downloads:/downloads
    ports:
      - 9117:9117
    networks:
      jackett-net:
    restart: unless-stopped
  
  flaresolverr:
    # DockerHub mirror flaresolverr/flaresolverr:latest
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    environment:
      - LOG_LEVEL=info
      - LOG_HTML=false
      - CAPTCHA_SOLVER=none
      - TZ=Europe/Rome
    ports:
      - 8191:8191
    networks:
      jackett-net:
    restart: unless-stopped 

networks:
  jackett-net:

volumes:
  qbit-config:
  jackett-config:
  downloads:
  torrents: