web:
  config:
    external_apps:
      - id: preview
        path: web-app-preview
        config:
          mimeTypes:
            - image/tiff
            - image/bmp
            - image/x-ms-bmp
      - id: importer
        path: web-app-importer
        config:
          companionUrl: https://companion.ocis-wopi.latest.owncloud.works
          supportedClouds:
            - WebdavPublicLink
            #- OneDrive # needs a client id and secret
            #- GoogleDrive # needs a client id and secret and an addition to the DNS zone
