version: "3.3"

services:
  traefik:
    image: traefik:v2.9.1
    container_name: traefik
    networks:
      proxy:
        aliases:
          - ${OCIS_DOMAIN}
          - ${WOPISERVER_DOMAIN}
          - ${COLLABORA_DOMAIN}
          - ${ONLYOFFICE_DOMAIN}
          - ${JELLYFIN_DOMAIN}
      monitor-net:
    command:
      - --log.level=ERROR
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --providers.docker
      #- --providers.docker.endpoint=unix:///var/run/docker.sock
      - --providers.docker.exposedByDefault=false
      - --api
      #- --certificatesresolvers.leresolver.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory
      - --certificatesresolvers.leresolver.acme.email=${EMAIL}
      - --certificatesresolvers.leresolver.acme.storage=/certs/acme.json
      - --certificatesresolvers.leresolver.acme.tlschallenge=true
      # enable prometheus
      - --metrics.prometheus=true
      - --metrics.prometheus.addEntryPointsLabels=true
      - --metrics.prometheus.addServicesLabels=true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "certs:/certs/"
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.traefik.rule=Host(`${DOMAIN}`)"
      - "traefik.http.routers.traefik.service=api@internal"
      - "traefik.http.routers.traefik.tls.certresolver=leresolver"
      - "traefik.http.routers.traefik.entrypoints=websecure"

      # add auth middleware
      - "traefik.http.routers.traefik.middlewares=traefik-auth"
      # you need to replace $ with $$ !
      - "traefik.http.middlewares.traefik-auth.basicauth.users=${BASIC_AUTH}"

      # global redirect to https
      - "traefik.http.routers.http-catchall.rule=hostregexp(`{host:.+}`)"
      - "traefik.http.routers.http-catchall.entrypoints=web"
      - "traefik.http.routers.http-catchall.middlewares=redirect-to-https"

      # middleware redirect
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
    logging:
      driver: "local"
    restart: unless-stopped

  homepage:
    image: ghcr.io/benphelps/homepage:latest
    container_name: homepage
    networks:
      proxy:
    volumes:
      - /home/simone/containers/traefik/homepage-config:/app/config
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.homepage.rule=Host(`${PUBLIC_HOMEPAGE_DOMAIN}`)"
      - "traefik.http.routers.homepage.entrypoints=websecure"
      - "traefik.http.routers.homepage.tls.certresolver=leresolver"
      - "traefik.http.routers.homepage.tls=true"
      - "traefik.http.services.homepage.loadbalancer.server.port=3000"
    logging:
      driver: "local"
    restart: unless-stopped

volumes:
  certs:


networks:
  proxy:
    external: true
  monitor-net:
    external: true
