version: "3.3"

services:
  traefik:
    image: traefik:v2.9.1
    container_name: traefik
    networks:
      proxy:
        aliases:
          - ${OCIS_DOMAIN}
          - ${WOPISERVER_DOMAIN}
          - ${COLLABORA_DOMAIN}
          - ${ONLYOFFICE_DOMAIN}
          - ${JELLYFIN_DOMAIN}
          - ${WALLABAG_DOMAIN}
      homepage-net:
    command:
      - --log.level=INFO
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --providers.docker
      #- --providers.docker.endpoint=unix:///var/run/docker.sock
      - --providers.docker.exposedByDefault=false
      - --api
      #- --certificatesresolvers.leresolver.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory
      - --certificatesresolvers.leresolver.acme.email=${EMAIL}
      - --certificatesresolvers.leresolver.acme.storage=/certs/acme.json
      - --certificatesresolvers.leresolver.acme.tlschallenge=true

      - --accesslog=true
      - --accessLog.filePath=/var/log/access.log
      - --accessLog.filters.statusCodes=400-499
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./logs:/var/log
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - certs:/certs/
    labels:
      traefik.enable: "true"
      traefik.docker.network: proxy
      traefik.http.routers.traefik.rule: "Host(`${TRAEFIK_DOMAIN}`)"
      traefik.http.routers.traefik.service: api@internal
      traefik.http.routers.traefik.tls.certresolver: leresolver
      traefik.http.routers.traefik.entrypoints: websecure

      # add auth middleware
      traefik.http.routers.traefik.middlewares: traefik-auth
      # you need to replace $ with $$ !
      traefik.http.middlewares.traefik-auth.basicauth.users: "${BASIC_AUTH}"

      # global redirect to https
      traefik.http.routers.http-catchall.rule: hostregexp(`{host:.+}`)
      traefik.http.routers.http-catchall.entrypoints: web
      traefik.http.routers.http-catchall.middlewares: redirect-to-https

      # middleware redirect
      traefik.http.middlewares.redirect-to-https.redirectscheme.scheme: https

      homepage.group: Network
      homepage.name: Traefik
      homepage.icon: traefik.svg
      homepage.href: https://${TRAEFIK_DOMAIN}
      homepage.widget.type: traefik
      homepage.widget.username: ${TRAEFIK_USER}
      homepage.widget.password: ${TRAEFIK_PASSWORD}
      homepage.widget.url: https://${TRAEFIK_DOMAIN}
    logging:
      driver: "local"
    restart: unless-stopped

volumes:
  certs:

networks:
  proxy:
    external: true
  homepage-net:
    external: true
