services:
  netdata:
    image: netdata/netdata:stable
    container_name: netdata
    pid: host
    network_mode: host
    cap_add:
      - SYS_PTRACE
      - SYS_ADMIN
    security_opt:
      - apparmor:unconfined
    volumes:
      - ./netdataconfig/netdata:/etc/netdata
      - netdatalib:/var/lib/netdata
      - netdatacache:/var/cache/netdata
      - /etc/passwd:/host/etc/passwd:ro
      - /etc/group:/host/etc/group:ro
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /etc/os-release:/host/etc/os-release:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      NETDATA_EXTRA_APK_PACKAGES: lm-sensors
    labels:
      homepage.group: Update & Monitor
      homepage.name: Netdata
      homepage.icon: netdata.svg
      homepage.href: https://app.netdata.cloud/
    restart: unless-stopped
    logging:
      driver: "local"

  scrutiny:
    container_name: scrutiny
    image: ghcr.io/analogj/scrutiny:master-omnibus
    cap_add:
      - SYS_RAWIO
    ports:
      - "7534:8080" # webapp
      - "7535:8086" # influxDB admin
    volumes:
      - /run/udev:/run/udev:ro
      - ./config:/opt/scrutiny/config
      - ./influxdb:/opt/scrutiny/influxdb
    devices:
      - "/dev/sda"
      - "/dev/sdb"
    networks:
      homepage-net:
    labels:
      homepage.group: Update & Monitor
      homepage.name: Scrutiny
      homepage.icon: scrutiny.svg
      homepage.href: http://localhost:7534/
      homepage.widget.type: scrutiny
      homepage.widget.url: http://scrutiny:8080
    restart: unless-stopped
    logging:
      driver: "local"


  speedtest-tracker:
    image: 'ghcr.io/alexjustesen/speedtest-tracker:latest'
    container_name: speedtest-tracker
    ports:
      - '4674:80'
      - '4675:443'
    networks:
      homepage-net:
      speedtest-net:
    environment:
      PUID: 1000
      PGID: 1000
      DB_CONNECTION: pgsql
      DB_HOST: speedtest-tracker-db
      DB_PORT: 5432
      DB_DATABASE: speedtest_tracker
      DB_USERNAME: speedy
      DB_PASSWORD: password
      TZ: Europe/Rome
      #APP_KEY: OLTzZ+zxMZmIbUQ60ZqpYYz9GyqiczbuH5U2TWyji60=
    labels:
      homepage.group: Network
      homepage.name: Speedtest tracker
      homepage.icon: si-speedtest.svg
      homepage.href: http://localhost:4674
      homepage.widget.type: speedtest
      homepage.widget.url: http://speedtest-tracker:80
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./speedtest-tracker/config:/config
      - ./speedtest-tracker/web:/etc/ssl/web
    depends_on:
      - speedtest-tracker-db
    restart: unless-stopped
    logging:
      driver: "local"

  speedtest-tracker-db:
    image: postgres:15
    container_name: speedtest-tracker-db
    environment:
      POSTGRES_DB: speedtest_tracker
      POSTGRES_USER: speedy
      POSTGRES_PASSWORD: password
    volumes:
      - speedtest-db:/var/lib/postgresql/data
    networks:
      speedtest-net:
    restart: unless-stopped
    logging:
      driver: "local"

volumes:
  netdatalib:
  netdatacache:
  speedtest-db:

networks:
  speedtest-net:
  homepage-net:
    external: true
