version: '3'
services:
  netdata:
    image: netdata/netdata:stable
    container_name: netdata
    pid: host
    network_mode: host
    cap_add:
      - SYS_PTRACE
      - SYS_ADMIN
    security_opt:
      - apparmor:unconfined
    volumes:
      - ./netdataconfig/netdata:/etc/netdata
      - netdatalib:/var/lib/netdata
      - netdatacache:/var/cache/netdata
      - /etc/passwd:/host/etc/passwd:ro
      - /etc/group:/host/etc/group:ro
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /etc/os-release:/host/etc/os-release:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      NETDATA_EXTRA_APK_PACKAGES: lm-sensors
    labels:
      homepage.group: Update & Monitor
      homepage.name: Netdata
      homepage.icon: netdata.svg
      homepage.href: https://app.netdata.cloud/
    restart: unless-stopped

  scrutiny:
    container_name: scrutiny
    image: ghcr.io/analogj/scrutiny:master-omnibus
    cap_add:
      - SYS_RAWIO
    ports:
      - "7534:8080" # webapp
      - "7535:8086" # influxDB admin
    volumes:
      - /run/udev:/run/udev:ro
      - ./config:/opt/scrutiny/config
      - ./influxdb:/opt/scrutiny/influxdb
    devices:
      - "/dev/sda"
      - "/dev/sdb"
      - "/dev/sdc"
    networks:
      homepage-net:
    labels:
      homepage.group: Update & Monitor
      homepage.name: Scrutiny
      homepage.icon: scrutiny.svg
      homepage.href: http://localhost:7534/
      homepage.widget.type: scrutiny
      homepage.widget.url: http://scrutiny:8080
    restart: unless-stopped

volumes:
  netdatalib:
  netdatacache:

networks:
  homepage-net:
    external: true
