# yaml-language-server: $schema=https://raw.githubusercontent.com/compose-spec/compose-spec/master/schema/compose-spec.json

version: "3"

services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    ports:
      - 8000:8000
      - 9443:9443
    networks:
      homepage-net:
      internal:
    volumes:
      - portainer-data:/data
    logging:
      driver: "local"
    labels:
      homepage.group: Network
      homepage.name: Portainer
      homepage.icon: portainer.svg
      homepage.href: https://localhost:9443
      homepage.widget.type: portainer
      homepage.widget.url: https://portainer:9443
      homepage.widget.env: 8
      homepage.widget.key: ${PORTAINER_API_KEY}
    restart: unless-stopped

  agent:
    image: portainer/agent:2.16.2
    container_name: portainer_agent
    ports:
      - 9001:9001
    networks:
      internal:
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    logging:
      driver: "local"
    restart: unless-stopped

volumes:
  portainer-data:

networks:
  homepage-net:
    external: true
  internal:
