version: "3.1"
services:

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=1002
      - PGID=1002
      - TZ=Europe/Rome
      - WEBUI_PORT=8078
    volumes:
      - qbit-config:/config
      - qbit-torrents:/torrents
      - /data/hdd/media-lib/torrents:/data/torrents
      - ./engines:/config/qBittorrent/nova3/engines
    ports:
      - 8078:8078
      - 6881:6881
      - 6881:6881/udp
    networks:
      media:
    logging:
      driver: "local"
    restart: unless-stopped

  jackett:
    image: lscr.io/linuxserver/jackett:latest
    container_name: jackett
    environment:
      - PUID=1002
      - PGID=1002
      - TZ=Europe/Rome
      - AUTO_UPDATE=true
        #optional
        #- RUN_OPTS=<run options here> #optional
    volumes:
      - jackett-config:/config
      - jackett-downloads:/downloads
    ports:
      - 9117:9117
    networks:
      media:
    logging:
      driver: "local"
    restart: unless-stopped

  flaresolverr:
    # DockerHub mirror flaresolverr/flaresolverr:latest
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    environment:
      - LOG_LEVEL=info
      - LOG_HTML=false
      - CAPTCHA_SOLVER=none
      - TZ=Europe/Rome
    ports:
      - 8191:8191
    networks:
      media:
    logging:
      driver: "local"
    restart: unless-stopped

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:develop
    container_name: prowlarr
    environment:
      - PUID=1002
      - PGID=1002
      - TZ=Europe/Rome
      - UMASK=002
    volumes:
      - prowlarr-config:/config
    ports:
      - "9696:9696"
    networks:
      media:
    logging:
      driver: "local"
    restart: unless-stopped

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1002
      - PGID=1002
      - TZ=Europe/Rome
      - UMASK=002
    volumes:
      - sonarr-config:/config
      - /data/hdd/media-lib:/data
    ports:
      - "8989:8989"
    networks:
      media:
    logging:
      driver: "local"
    restart: unless-stopped

  radarr:
    image: cr.hotio.dev/hotio/radarr
    container_name: radarr
    environment:
      - PUID=1002
      - PGID=1002
      - TZ=Europe/Rome
      - UMASK=002
    volumes:
      - radarr-config:/config
      - /data/hdd/media-lib:/data
    ports:
      - "7878:7878"
    networks:
      media:
    logging:
      driver: "local"
    restart: unless-stopped

  readarr:
    image: lscr.io/linuxserver/readarr:develop
    container_name: readarr
    environment:
      - PUID=1002
      - PGID=1002
      - TZ=Europe/Rome
      - UMASK=002
    volumes:
      - readarr-config:/config
      - /data/hdd/media-lib:/data
    ports:
      - "8787:8787"
    networks:
      media:
    logging:
      driver: "local"
    restart: unless-stopped

  jellyseerr:
    image: fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    environment:
      - LOG_LEVEL=debug
      - TZ=Europe/Rome
    ports:
      - 5055:5055
    networks:
      media:
      proxy:
    volumes:
      - ./jellyseerr_logs:/app/config/logs
      - jellyseerr-config:/app/config
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"

      - "traefik.http.routers.jellyseerr.rule=Host(`${JELLYSEERR_DOMAIN}`)"
      - "traefik.http.routers.jellyseerr.entryPoints=websecure"

      - "traefik.http.routers.jellyseerr.tls.certresolver=leresolver"
      - "traefik.http.routers.jellyseerr.tls=true"
      - "traefik.http.routers.jellyseerr.service=jellyseerr-svc"
      - "traefik.http.services.jellyseerr-svc.loadbalancer.server.port=5055"

      - homepage.group=Media
      - homepage.name=Discover
      - homepage.icon=https://raw.githubusercontent.com/walkxcode/dashboard-icons/main/svg/jellyseerr.svg
      - homepage.href=https://${JELLYSEERR_DOMAIN}
      - homepage.description=Discover media and request it
    logging:
      driver: "local"
    restart: unless-stopped

networks:
  media:
    external: true
  proxy:
    external: true

volumes:
  qbit-config:
    external: true
  qbit-torrents:
    external: true
  jackett-config:
    external: true
  jackett-downloads:
    external: true
  prowlarr-config:
    external: true
  sonarr-config:
    external: true
  radarr-config:
    external: true
  readarr-config:
    external: true
  jellyseerr-config:
    external: true
