version: "3"

services:
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/localtime:/etc/localtime:ro
    environment:
      WATCHTOWER_NOTIFICATION_REPORT: "true"
      WATCHTOWER_NOTIFICATION_URL: "telegram://${TOKEN}@telegram?chats=${CHAT}"
      WATCHTOWER_POLL_INTERVAL: "3600"
    logging:
      driver: "local"
    restart: unless-stopped

  apprise:
    image: caronc/apprise:latest
    container_name: apprise
    networks:
      - apprise
    ports:
      - 8005:8000
    volumes:
      - ./apprise_config:/config
    logging:
      driver: "local"
    restart: unless-stopped

networks:
  apprise:
    external: true

