sut:
  build: .
  command: sh -c '(qbittorrent-nox &) && sleep 5 && curl --max-time 10 --retry 10 --retry-max-time 60 --retry-connrefused --connect-timeout 5 --silent --show-error --fail http://localhost:8080/ >/dev/null || exit 1'
